### ISSUE TITLE
Error received when tapping "Learn more" on Welcome page in Sample App

### ISSUE THREAD

**Issue by crayne** [ResearchStack/ResearchStack#203]
Error on emulator (Genymotion api 23) is:
``Webpage not available
The webpage at
file:///android_res/raw/consent_section_html_welcome.html
could not be loaded because
net::ERR_FILE_NOT_FOUND
``
Error in log is:
``
Not allowed to load local resource: file:///android_res/raw/consent_section_html_welcome.html", source: data:text/html,chromewebdata (0)
``

**Comment by wdziemia** [comment]
@crayne We changed the location of where you assets are, they should be in the assets folder now. Its alot more flexible than defining all files within raw. Additionally, you should be able to drag and drop your content in RK app without having to change filenames. As for images, they can be in the root of the HTML OR you can define the absolute drawable path like we had before. 

Take a look at the Sample App SampleResourceManager to see the new changes

**Comment by crayne** [comment]
I pulled the latest SampleApp files and the problem is gone.  I moved all my GlucoSuccess files to the assets folder -- now I just need to compare the GlucoSuccess files to the latest SampleApp files and apply the changes.  Thanks for your help.
