### ISSUE TITLE
Install Skin fails

### ISSUE THREAD

**Issue by crayne** [ResearchStack/ResearchStack#207]
Install Skin fails with build.gradle files just pulled (with all source) from this repo.  Install Backbone succeeds.  Errors:
````
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':skin:compileReleaseJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

2: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':skin:compileRetrolambdaRelease'.
> Directory '/Users/susancrayne/ResearchStack/ResearchStack/skin/build/retrolambda/release' specified for property 'inputDir' does not exist.
````
JAVA_HOME is set to the correct directory

**Comment by crayne** [comment]
Is there perhaps a workaround for this?

**Comment by wdziemia** [comment]
You shouldn't need to build skin / backbone locally anymore. Your project should be pointing to the following:

```
compile 'org.researchstack:backbone:1.0.0.rc1'
compile 'org.researchstack:skin:1.0.0.rc1'
```

If you need to build RS source, make sure JAVA8_HOME is also set. What version of studio are you running, v2.1 beta?

**Comment by crayne** [comment]
I understand now that the RS libraries are in a remote repository.  I updated to v2.1 Beta 3 and the install skin build succeeds. Thank you.

**Comment by wdziemia** [comment]
Not a problem, glad you got it working
