### ISSUE TITLE
Best way to add a picture in a step layout

### ISSUE THREAD

**Issue by dariosalviwork** [ResearchStack/ResearchStack#259]
Hi,

this a question not really an issue, but it would be nice to have it documented here.

I need to create a simple layout with a text and an image.
I am copying the rsb_step_layout_instructions.xml and I would like to add a picture too below the main text.
What element would you suggest me to put below the rsb_intruction_text?

What if I want the image to be themeable (as you did in the sample app, where you can customise the colours) ?

As far as I've understood, if my StepLayout then extends FixedSubmitBarLayout, then I would also inherit a button bar below.

What if I want just one button below and not two?

Cheers.

**Comment by jdkizer9** [comment]
Hi @dariosalviwork,

I've been working on a [library](https://github.com/cornelltech/sdl-rsx) that extends ResearchStack by providing a set visual surveys developed by the [Small Data Lab](http://smalldata.io/). I'd love to know what you think, if they fit your needs, why/why not, etc. Any and all feedback is appreciated. I'm also working on a blog post on the design of the library which may be of use as well.

Best
James

**Comment by dariosalviwork** [comment]
I think that this issue is not relevant any more.
As for the image: I have used [this tool](http://romannurik.github.io/AndroidAssetStudio/index.html) to create the images from a source, then placed the image inside an ImageView inside the layout of my Step. The layout is initialised with a grey image like here:

 ```
   <ImageView
        android:id="@+id/intro_img_img"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:scaleType="centerInside"
        tools:src="@drawable/rsb_debug_gray"
        tools:visibility="visible"
        />
```

Then the actual image is retrieved from the resources, its color changed, and visualised like done here:

```
       // Set Image
        TypedValue typedValue = new TypedValue();
        TypedArray a = getContext().obtainStyledAttributes(typedValue.data,
                new int[] {org.researchstack.backbone.R.attr.colorAccent});
        int accentColor = a.getColor(0, 0);
        a.recycle();

        final ImageView imageView = (ImageView) findViewById(R.id.intro_img_img);

        Drawable image = getResources().getDrawable(step.getImageId());
        image = DrawableCompat.wrap(image);
        DrawableCompat.setTint(image, accentColor);
        imageView.setImageDrawable(image);

        imageView.setVisibility(View.VISIBLE);
```

The actual image id is stored in a class that extends Step.
