### ISSUE TITLE
Integrating library as a local module dependency

### ISSUE THREAD

**Issue by haorlin** [ResearchStack/ResearchStack#260]
I wanted to make a few changes to the ResearchStack java files 
Has anyone found a working way of doing that?

I tried to simply 
1. Download the library off of github
2. Include ':ResearchStack:skin' in settings.gradle. I also tried just ':ResearchStack' also.
3. Added :ResearchStack:skin to the module dependencies

![image](https://cloud.githubusercontent.com/assets/10675113/16398577/43b88aca-3c80-11e6-8ea7-70f92fa4fbf2.png)

Another issue is that some of the plugins could not be found.
![image](https://cloud.githubusercontent.com/assets/10675113/16398581/4bbc135e-3c80-11e6-9811-5d71a268ece0.png)

**Comment by wdziemia** [comment]
**Building Locally:**

- Open the ResearchStack project in Android Studio
- go to the build.gradle files for both skin and backbone. You need to change the version to something else other than `version = '1.0.0.rc1'`, as thats the "official" version. (change to `version = '1.0.0.rc1-haorlin'`)
- Go to Run > Edit Configurations...
- Add new configuration (plus icon)
- Choose Gradle as the configuration type
- Set a name(e.g. "Deploy Backbone locally")
- Choose the /backbone/build.gradle file as the "Gradle project" field
- Add "install" to the tasks field
- Save
- Run that configuration and check ~/.m2 to see if it deployed
- Repeat with /skin/build.gradle
- Open your own Android Studio project and follow the instructions below to add these newly-deployed libraries as dependencies.

Now create a new Android Studio project. Within the **project's** build.gradle you need to add `mavenLocal` to places where the project can look up the project. Like So:
```
buildscript {
    repositories {
        mavenLocal()
        .....
    }
    .......
}

allprojects {
    ......
}
```
    
then in the **app's** build.gradle, you can import the project via the following line:

`compile 'org.researchstack:skin:1.0.0.rc1-haorlin'`

Note: You need to run the maven local install script each time you make a change to your version of RS. You then rebuild your project and should be good to go. 

Enjoy :)

**Comment by mikecarroll** [comment]
Thanks @wdziemia! Closing this one.

**Comment by haorlin** [comment]
That worked, thanks a lot @wdziemia !
