### ISSUE TITLE
Pull request versioning and release policy

### ISSUE THREAD

**Issue by liujoshua** [ResearchStack/ResearchStack#280]
What is the guidance for versioning when submitting pull requests? Should each request bump the version (major, minor, or patch, as appropriate) for immediate release or will changes be batched for release? If the latter, should pull requests target development branch(es) for collecting the non-releasable changes?

**Comment by mikecarroll** [comment]
@liujoshua We are still coming up with good guidelines but, yes, each request would bump the version (as appropriate) -- a critical bug fix we'd release immediately as a patch, feature PRs we may hold to bundle together into minor (or possibly major) release.

For now, I would target development branches with all PRs. Fortunately, Github let's us change the target branch for PRs now, so we can always switch to what's more appropriate later.
