### ISSUE TITLE
SQLCipher dependency needs update for Android N

### ISSUE THREAD

**Issue by liujoshua** [ResearchStack/ResearchStack#282]
This is an **urgent** and **mandatory** upgrade for applications wishing to support Android N when it is publicly released.

https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465

**Comment by liujoshua** [comment]
I'm testing the upgrade to 'net.zetetic:android-database-sqlcipher:3.5.1@aar' via our fork of the Sample App and will post an update here

**Comment by dukemike** [comment]
net.zetetic:android-database-sqlcipher:3.5.4@aar seems to be working fine for me.

**Comment by petriet** [comment]
I added 3.5.1 to our fork of RS for Android Mole Mapper and preliminary testing seems fine.
