### ISSUE TITLE
allow pin to be cleared

### ISSUE THREAD

**Issue by dukemike** [ResearchStack/ResearchStack#283]
In my apps, I would like to clear the pin when the user signs out or withdraws so that I can fully reset the app to its initial state.

**Comment by dukemike** [comment]
PR #286 resolves this issue and was accepted.

**Comment by bosniltd-a11y** [comment]
> In my apps, I would like to clear the pin when the user signs out or withdraws so that I can fully reset the app to its initial state.
>
