### ISSUE TITLE
List of apps using ResearchStack?

### ISSUE THREAD

**Issue by swaffoja** [ResearchStack/ResearchStack#298]
I know [MoleMapper](https://tech.cornell.edu/news/first-researchstack-app-molemapper-launches-on-android) uses ResearchStack. Are there any other apps using ResearchStack?

**Comment by dukemike** [comment]
@swaffoja We plan to release an app in the next few months for both iOS and Android.

**Comment by swaffoja** [comment]
@dukemike Thanks!
