### ISSUE TITLE
Next button does not act as expected in FormStep

### ISSUE THREAD

**Issue by SamUndefined** [ResearchStack/ResearchStack#354]
A few of our users expected the next button to tab from one textfield to the next (shift focus) in a FormStep. Instead it attempts to submit the document (displaying a toast that says "Invalid answer, try again!" since the form is incomplete). What might be a good way to change this behavior?

**Comment by dephillipsmichael** [comment]
IMO, the shortest solution would be to change the submit bar's "next" button to say "done" so the user experience isn't misleading.

However, your ultimate goal is automatically moving focus to the next focusable element on the screen.  That should only happen after the IME_ACTION_NEXT button on the keyboard is tapped, not any submit bar button.  Unfortunately, that functionality doesn't exist in the master branch of ResearchStack.  However, it is something I added when I refactored the FormStepLayout on the develop branch. If you want some guidance on how to accomplish it and add it to your app before the develop branch is released, see the setupEditTextImeOptions method of this class...

https://github.com/ResearchStack/ResearchStack/blob/develop/backbone/src/main/java/org/researchstack/backbone/ui/step/layout/FormStepLayout.java
