### ISSUE TITLE
Keyboard appears on non-text entry steps

### ISSUE THREAD

**Issue by suomi35** [ResearchStack/ResearchStack#359]
I am experiencing the keyboard showing on custom non-text entry steps.
When a step requiring the keyboard is completed, every other step thereafter will have the keyboard pop back up. It makes for pretty annoying UX.

Is there any workaround to prevent this from happening?
All of my steps are custom, extending Step, with layouts implementing StepLayout.

**Comment by liujoshua** [comment]
Which version/commit of ResearchStack are you using?

Could you please attach a screenshot? And if your repository is public, a link to the layout, Step and StepLayout with the keyboard inappropriately popping up?

**Comment by gitspider** [comment]
I have same issue. I guess the following line is the reason.

imm.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0); 
// StepSwitcher.java ln:160-163

**Comment by gitspider** [comment]
The bug is occurred on especially Samsung Galaxy S4 phone.

**Comment by jdkizer9** [comment]
@liujoshua I'm experiencing the same issue. I've been able to reproduce on the nexus 5x emulator running API 21. Repo [here](https://github.com/smalldatalab/northwell-impulse-android).

**Comment by liujoshua** [comment]
Thank you all for bringing this to our attention. I've entered it into our internal JIRA as a high priority bug.

**Comment by dephillipsmichael** [comment]
I fixed this issue on the develop branch, see the PR https://github.com/ResearchStack/ResearchStack/pull/374

Here is a screenshot of the changes for the lazy
<img width="758" alt="screen shot 2017-04-08 at 4 06 08 pm" src="https://cloud.githubusercontent.com/assets/5590748/24832068/af170f50-1c75-11e7-9aad-0e1b70f8b874.png">

**Comment by jdkizer9** [comment]
Thanks for this!!
