### ISSUE TITLE
Is it possible to use custom steps in a FormStep?

### ISSUE THREAD

**Issue by suomi35** [ResearchStack/ResearchStack#369]
I am trying to create a Form step with custom steps. I am met with a serialization issue, however:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.example/org.researchstack.backbone.ui.ViewTaskActivity}: java.lang.RuntimeException: Parcelable encountered IOException reading a Serializable object (name = org.researchstack.backbone.task.OrderedTask)`

Everything is serializable on both sides, as far as I can tell. Any ideas?

**Comment by jdkizer9** [comment]
@suomi35, see [this](https://github.com/smalldatalab/northwell-impulse-android/blob/master/app/src/main/java/org/smalldatalab/northwell/impulse/SDL/CTFLikertFormStepGenerator.java) for a working implementation. If you add some more info, I might be able to help troubleshoot.

**Comment by dephillipsmichael** [comment]
It's hard to say without seeing the code for you CustomSteps, but if I had to guess it would be that one of them does not fully implement Serializable.  For Serializable to work, you must provide a default constructor for that class and make sure that all the member variables of your CustomSteps are also Serializable.

**Comment by suomi35** [comment]
I was able to get this working. I was using only StepLayout instead of a StepBody. I converted all of my custom steps to use StepBody and it works fine now.

Thanks @jdkizer9 for the example!
