### ISSUE TITLE
Saving Results of Surveys

### ISSUE THREAD

**Issue by luckysharms9** [ResearchStack/ResearchStack#378]
I'm trying to save results of surveys, parsed in another class that I've created, however the code never goes to the onActivityResult.
Can anyone show me how to save results from surveys correctly?
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
                if(requestCode == REQUEST_SURVEY && resultCode == RESULT_OK) {
                    EESurveyManager.calculateTotalSurveyScoreFromResults((TaskResult) data.getSerializableExtra(ViewTaskActivity.EXTRA_TASK_RESULT));
                }
    }

**Comment by jdkizer9** [comment]
Hi @luckysharms9, I'd have to see more of your project to have a better idea of what's going on. Is it publicly available? You might also want to check out the [Backbone Example App](https://github.com/ResearchStack/BackboneExampleApp) for an example of how to launch a Task and process the results (See MainActivity.java).

Hope this helps!!

**Comment by luckysharms9** [comment]
Here are the two files that I'm working with right now, I want to save the results from the survey being taken. I have tried debugging to no avail, the survey never reaches the onActivityResult method.

**Comment by jdkizer9** [comment]
I try not to open zip files from strangers (as my grandpa used to always say). Can you point me to a repo / gist by any chance?

**Comment by luckysharms9** [comment]
Sorry, it's on a private repository. Here they are as text files.
[survey.txt](https://github.com/ResearchStack/ResearchStack/files/1181126/survey.txt)
[surveymanager.txt](https://github.com/ResearchStack/ResearchStack/files/1181127/surveymanager.txt)

**Comment by jdkizer9** [comment]
Just taking a shot in the dark, and I'd need to actually run it to be sure, (and I'm kind of an Android noob) but it looks like you are calling finish() on your AnxietySurvey activity immediately after you launch your ResearchStack task. Doing that kills the activity, so there is nothing to send the result to. You need to wait until you've processed your results before you call finish.

Did this fix the problem?

**Comment by jdkizer9** [comment]
closing this as not a ResearchStack issue

**Comment by luckysharms9** [comment]
Right, I am however getting an error saving the results. How can I print the results from the survey in the terminal/monitor for testing purposes?

**Comment by jdkizer9** [comment]
@luckysharms9 Take a look at the Backbone Example App for an example of how to launch a Task and process the results (See MainActivity.java).

**Comment by luckysharms9** [comment]
How can we extract the values as strings/integers? Right now they are printing back on the console as blocks of memory, I'm assuming.

i.e. questionone_step @2980fe3

**Comment by dukemike** [comment]
@luckysharms9 If I understand what you're asking, here's sample code from the RS Sample app's `BridgeEncryptedDatabase`.

```java
Gson gson = new GsonBuilder().setDateFormat(FormatHelper.DATE_FORMAT_ISO_8601).create();

for (StepResult stepResult : taskResult.getResults().values()) {
    Log.i(TAG, "saving task result");
    if (stepResult != null) {
        StepRecord stepRecord = new StepRecord();
        stepRecord.taskId = taskResult.getIdentifier();
        stepRecord.stepId = stepResult.getIdentifier();
        stepRecord.completed = stepResult.getEndDate();
        if (!stepResult.getResults().isEmpty()) {
            stepRecord.result = gson.toJson(stepResult.getResults());
        }
    }
}
```

where `StepRecord` is being used to persist the task result to SQLite.

You can also things like:

```java
StepResult selectionStepResult = taskResult.getStepResult("q1");
Object[] answers = (Object[]) selectionStepResult.getResultForIdentifier("answer");
```
