### ISSUE TITLE
Still actively maintained?

### ISSUE THREAD

**Issue by nstrelow** [ResearchStack/ResearchStack#529]
Is ResearchStack still actively maintained and does it make sense to use it?

Are there any alternatives?

Looking into building a cross-platform research app using Flutter.

It uses ResearchStack for Android and ResearchKit for IOS: https://pub.dev/packages/research_package

**Comment by davwillev** [comment]
Hi @nstrelow 
It is actively maintained but the wheels turn quite slowly :)
